### ISSUE TITLE
Error in running basenji_data.py

### ISSUE THREAD

**Issue by luohaitaofujian** [calico/basenji#134]
Hello!When I run the basenji_data.py,I met some problems.
python basenji_data.py -d .1 -g data/unmap_macro.bed -l 196608 --local -o data/heart_l131k -p 8 -t .1 -v .1 -w 128 data/test.fna data/heart_wigs.txt
(the test.fna is a bacteria genome)

stride_train 1 converted to 196608.000000
stride_test 1 converted to 196608.000000
Contigs divided into
 Train:    15 contigs,    7856972 nt (1.0000)
 Valid:     0 contigs,          0 nt (0.0000)
 Test:      0 contigs,          0 nt (0.0000)
python basenji_data_read.py -w 128 -u sum -c 0.000000 -s 1.000000 data/out.bw data/heart_l131k/sequences.bed data/heart_l131k/seqs_cov/0.h5
Traceback (most recent call last):
  File "/root/luoht/preprocess/basenji_data.py", line 951, in <module>
    main()
  File "/root/luoht/preprocess/basenji_data.py", line 421, in main
    fold_set_start = fold_set_indexes[0]
IndexError: list index out of range

1.Why the valid and test are 0 contigs?
2.How can I deal with the indexerror?

Thank you!

**Comment by davek44** [comment]
It looks like you're providing a FASTA file that doesn't match the BED file data/unmap_macro.bed or the BigWig files in data/heart_wigs.txt
