### ISSUE TITLE
Training crashes 

### ISSUE THREAD

**Issue by laurajb** [calico/basenji#14]
Hello, 

I am trying to train a model but I get a bunch of warnings from tensorflow and then it crashes, I don't know if this might be a tensorflow compatibility issue, I am using tensorflow 1.7
Any ideas? Thanks in advance! 

/home/laura/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
2018-04-20 19:06:34.278450: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{'batch_size': 2, 'seq_length': [262144, 65536], 'seq_depth': 4, 'target_length': 2048, 'num_targets': 10, 'target_pool': 128, 'batch_buffer': 16384, 'batch_renorm': 1, 'link': 'exp_linear', 'loss': 'poisson', 'learning_rate': 0.005769, 'momentum': 0.99574, 'optimizer': 'momentum', 'cnn_dropout': 0.04375, 'cnn_l2': 1.44e-09, 'cnn_filter_sizes': [3, 1, 3, 3, 3, 3], 'cnn_filters': [6, 6, 6, 6, 6, 376], 'cnn_pool': [1, 2, 4, 4, 4, 1], 'dense': 1, 'dcnn_dropout': 0.072917, 'dcnn_l2': 1.93e-08, 'dcnn_filter_sizes': [3, 3, 3, 3, 3, 3, 3], 'dcnn_filters': [8, 8, 8, 8, 8, 8, 8], 'full_units': 32, 'full_dropout': 0.009375, 'full_l2': 2.58e-08, 'final_l1': 1.45e-08, 'load_hd5': 1}
Targets pooled by 128 to length 2048
Convolution w/ 10 376x1 filters to final targets
Model building time 59.275235
Batcher initialized
Initializing...
Initialization time 0.484647
Traceback (most recent call last):
  File "bin/basenji_train.py", line 207, in <module>
    tf.app.run(main)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "bin/basenji_train.py", line 40, in main
    num_train_epochs=FLAGS.num_train_epochs)
  File "bin/basenji_train.py", line 145, in run
    for epoch in range(num_train_epochs):
TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by davek44** [comment]
It's crashing because it doesn't have a value for the num_train_epochs flag. Previously, the default was None. I just pushed a new commit that sets the default value to 1000. Grab that and try again.

**Comment by laurajb** [comment]
Hi Dave,

After using the updated script I was able to run **basenji_train.py** with the example data you provide, however when trying to train on my own data I get the following: 

/home/laura/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:From /home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py:497: calling conv1d (from tensorflow.python.ops.nn_ops) with data_format=NHWC is deprecated and will be removed in a future version.
Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead
2018-07-09 16:31:11.696187: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{'batch_size': 2, 'seq_length': [262144, 65536], 'seq_depth': 4, 'target_length': 2048, 'num_targets': 10, 'target_pool': 128, 'batch_buffer': 16384, 'batch_renorm': 1, 'link': 'exp_linear', 'loss': 'poisson', 'learning_rate': 0.005769, 'momentum': 0.99574, 'optimizer': 'momentum', 'cnn_dropout': 0.04375, 'cnn_l2': 1.44e-09, 'cnn_filter_sizes': [3, 1, 3, 3, 3, 3], 'cnn_filters': [6, 6, 6, 6, 6, 376], 'cnn_pool': [1, 2, 4, 4, 4, 1], 'dense': 1, 'dcnn_dropout': 0.072917, 'dcnn_l2': 1.93e-08, 'dcnn_filter_sizes': [3, 3, 3, 3, 3, 3, 3], 'dcnn_filters': [8, 8, 8, 8, 8, 8, 8], 'full_units': 32, 'full_dropout': 0.009375, 'full_l2': 2.58e-08, 'final_l1': 1.45e-08, 'load_hd5': 1}
Targets pooled by 128 to length 1024
Convolution w/ 117 376x1 filters to final targets
Model building time 60.624662
Batcher initialized
Initializing...
Initialization time 0.726727
Epoch:   1,  Steps:    1663,  Train loss: 123.11291,  Valid loss: 82.75806,  Valid R2: 0.07725,  Time: 526s, best!
Epoch:   2,  Steps:    3326,  Train loss: 103.79168,  Valid loss: 83.82111,  Valid R2: 0.07265,  Time: 546s
Epoch:   3,  Steps:    4989,  Train loss: 103.25912,  Valid loss: 80.70190,  Valid R2: 0.09421,  Time: 538s, best!
Epoch:   4,  Steps:    6652,  Train loss: 102.04881,  Valid loss: 79.70689,  Valid R2: 0.10218,  Time: 554s, best!
Epoch:   5,  Steps:    8315,  Train loss: 101.50900,  Valid loss: 85.45751,  Valid R2: 0.05753,  Time: 534s
Traceback (most recent call last):
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1312, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1420, in _call_tf_sessionrun
    status, run_metadata)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loss : Tensor had NaN values
         [[Node: loss_check = CheckNumerics[T=DT_FLOAT, message="Invalid loss", _device="/job:localhost/replica:0/task:0/device:CPU:0"](target_loss)]]

Is there something wrong with the h5 file? Thanks in advance!

Laura

**Comment by davek44** [comment]
Hi Laura,

First, you encountered quite a few warnings there. Are you using version 1.8 of TensorFlow? You might update.

Second, it looks like you're using parameters from https://github.com/calico/basenji/blob/master/testdata/params.small.hd5.txt. That file refers to some internal tests (and was written by someone else). I recommend using these parameters: https://github.com/calico/basenji/blob/master/manuscript/params.txt. If the model is too big and overfits, just reduce the filter numbers.

Let me know if that helps.

Best,
Dave

**Comment by laurajb** [comment]
Hi Dave,

Sorry for taking so long to answer, my jobs take forever on the queue... I updated to tensorflow 1.8  (had 1.7) and used the different parameters file, now it doesn't crash because of NaNs but because of Inf values:

I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
{'batch_size': 2, 'batch_buffer': 4096, 'link': 'exp_linear', 'loss': 'poisson', 'adam_beta1': 0.97, 'adam_beta2': 0.98, 'learning_rate': 0.002063, 'cnn_filter_sizes': [22, 1, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 1], 'cnn_filters': [312, 368, 435, 514, 607, 717, 108, 108, 108, 108, 108, 108, 1365], 'cnn_pool': [1, 2, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1], 'cnn_dilation': [1, 1, 1, 1, 1, 1, 2, 4, 8, 16, 32, 64, 1], 'cnn_dropout': [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05], 'cnn_dense': [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]}
Targets pooled by 128 to length 1024
Convolution w/ 117 1365x1 filters to final targets
Model building time 45.841515
Batcher initialized
Initializing...
Initialization time 1.644151
Epoch:   1,  Steps:    1663,  Train loss: 103.31998,  Valid loss: 97.23989,  Valid R2: 0.07790,  Time: 3.2h, best!
Epoch:   2,  Steps:    3326,  Train loss: 90.06141,  Valid loss: 69.94243,  Valid R2: 0.19546,  Time: 3.2h, best!
/home/laura/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loss : Tensor had Inf values
     [[Node: loss_check = CheckNumerics[T=DT_FLOAT, message="Invalid loss", _device="/job:localhost/replica:0/task:0/device:CPU:0"](target_loss)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/laura/basenji/bin/basenji_train.py", line 207, in <module>
    tf.app.run(main)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/laura/basenji/bin/basenji_train.py", line 40, in main
    num_train_epochs=FLAGS.num_train_epochs)
  File "/home/laura/basenji/bin/basenji_train.py", line 162, in run
    augment_shifts[shift_i], train_writer, FLAGS.no_steps)
  File "/home/laura/basenji/basenji/seqnn.py", line 516, in train_epoch
    feed_dict=fd)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid loss : Tensor had Inf values
     [[Node: loss_check = CheckNumerics[T=DT_FLOAT, message="Invalid loss", _device="/job:localhost/replica:0/task:0/device:CPU:0"](target_loss)]]

Caused by op 'loss_check', defined at:
  File "/home/laura/basenji/bin/basenji_train.py", line 207, in <module>
    tf.app.run(main)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/laura/basenji/bin/basenji_train.py", line 40, in main
    num_train_epochs=FLAGS.num_train_epochs)
  File "/home/laura/basenji/bin/basenji_train.py", line 73, in run
    model.build(job)
  File "/home/laura/basenji/basenji/seqnn.py", line 43, in build
    self.build_from_data_ops(job, data_ops, target_subset)
  File "/home/laura/basenji/basenji/seqnn.py", line 55, in build_from_data_ops
    self.loss_op, self.loss_adhoc = self.build_loss(seqs_repr, data_ops, target_subset)
  File "/home/laura/basenji/basenji/seqnn.py", line 351, in build_loss
    loss_op = tf.check_numerics(loss_op, 'Invalid loss', name='loss_check')
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 737, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/laura/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Invalid loss : Tensor had Inf values
     [[Node: loss_check = CheckNumerics[T=DT_FLOAT, message="Invalid loss", _device="/job:localhost/replica:0/task:0/device:CPU:0"](target_loss)]

Best,
Laura

**Comment by davek44** [comment]
Hi Laura, can you try changing the link function from "exp_linear" to "softplus"? I've been using that lately, and it's possible that I haven't been sufficiently careful about avoiding overflows for exp_linear.
