### ISSUE TITLE
AssertionError, Basenji_test.py 'Conv1D' object has no attribute 'input_shape'

### ISSUE THREAD

**Issue by PouriaAzadehR** [calico/basenji#199]
Hi,

I follow up the installation instructions and test_train tutorial.
I used the pre-trained model and did not train a new one.

when running the following command

 ../bin/basenji_test.py --ai 0,1,2 -o output/heart_test --rc --shifts "1,0,-1" models/params_small.json models/heart/model_best.h5 heart_l131k
 
 I get error 
 
  Total params: 111,011 (433.64 KB)
 Trainable params: 109,235 (426.70 KB)
 Non-trainable params: 1,776 (6.94 KB)
None
Traceback (most recent call last):
  File "/project/6014832/pouria81/basenji/tutorials/../bin/basenji_test.py", line 433, in <module>
    main()
  File "/project/6014832/pouria81/basenji/tutorials/../bin/basenji_test.py", line 143, in main
    seqnn_model = seqnn.SeqNN(params_model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/6014832/pouria81/basenji/basenji/seqnn.py", line 35, in __init__
    self.build_model()
  File "/project/6014832/pouria81/basenji/basenji/seqnn.py", line 190, in build_model
    stride_factor = layer.input_shape[1] / layer.output_shape[1]

**Comment by davek44** [comment]
We're not maintaining this repository anymore. Please move to https://github.com/calico/baskerville

**Comment by enriquemondragon** [comment]
Hi Pouria and David,

I know it's been a while--but I created a pull request that solves this issue. Hope it helps: https://github.com/calico/basenji/pull/207

**Comment by davek44** [comment]
What version trigger this? Everything seems to run fine for me with tensorflow 2.15.1

**Comment by enriquemondragon** [comment]
In my case, I'm using tensorflow 2.17.0. The virtual environment in which I encountered this error was created by following the installation steps of [SuPreMo-Akita](https://github.com/ketringjoni/SuPreMo), which requires Basenji. Here is the requirements.txt of my venv, in case it is useful:

> absl-py==2.1.0
anyio==4.6.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asciitree==0.3.3
astropy==6.1.7
astropy-iers-data==0.2025.2.24.0.34.4
asttokens==2.0.5
astunparse==1.6.3
async-lru==2.0.4
attrs==24.3.0
babel==2.16.0
basenji==0.1
bctpy==0.6.1
beautifulsoup4==4.12.3
bioframe==0.7.2
biopython==1.85
bleach==6.2.0
Bottleneck==1.4.2
Brotli==1.0.9
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.8
comm==0.2.1
contourpy==1.3.1
cooler==0.10.3
cooltools==0.7.1
cycler==0.12.1
Cython==3.0.12
cytoolz==1.0.1
debugpy==1.8.11
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.9
exceptiongroup==1.2.0
executing==0.8.3
fastjsonschema==2.20.0
flatbuffers==24.3.25
fonttools==4.56.0
gast==0.5.3
google-pasta==0.2.0
grpcio==1.62.2
h11==0.14.0
h5py==3.12.1
httpcore==1.0.2
httpx==0.27.0
idna==3.7
imageio==2.37.0
importlib_metadata==8.6.1
intervaltree==3.1.0
ipykernel==6.29.5
ipython==8.30.0
ipywidgets==8.1.5
jax==0.5.1
jaxlib==0.5.1
jedi==0.19.2
Jinja2==3.1.5
joblib==1.4.2
json5==0.9.25
jsonschema==4.23.0
jsonschema-specifications==2023.7.1
jupyter==1.1.1
jupyter_client==8.6.3
jupyter-console==6.6.3
jupyter_core==5.7.2
jupyter-events==0.10.0
jupyter-lsp==2.2.0
jupyter_server==2.14.1
jupyter_server_terminals==0.4.4
jupyterlab==4.3.4
jupyterlab-pygments==0.1.2
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.13
keras==3.6.0
kiwisolver==1.4.8
lazy_loader==0.4
libclang==18.1.1
llvmlite==0.44.0
Markdown==3.4.1
markdown-it-py==2.2.0
MarkupSafe==3.0.2
matplotlib==3.8.4
matplotlib-inline==0.1.6
mdurl==0.1.0
mistune==2.0.4
mkl_fft==1.3.11
mkl_random==1.2.8
mkl-service==2.4.0
ml_dtypes==0.4.0
multiprocess==0.70.17
namex==0.0.7
natsort==8.4.0
nbclient==0.8.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.4.2
nibabel==5.2.1
notebook==7.3.2
notebook_shim==0.2.3
numba==0.61.0
numexpr==2.10.1
numpy==1.26.4
opt-einsum==3.3.0
optree==0.12.1
overrides==7.4.0
packaging==24.2
pandas==2.2.2
pandocfilters==1.5.0
parso==0.8.4
pathlib==1.0.1
patsy==1.0.1
pexpect==4.8.0
pillow==11.1.0
pip==25.0
platformdirs==3.10.0
prometheus_client==0.21.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
pybedtools==0.11.0
pyBigWig==0.3.24
pycparser==2.21
pyerfa==2.0.1.5
pyfaidx==0.8.1.3
Pygments==2.15.1
pyparsing==3.2.1
PyQt6==6.7.1
PyQt6_sip==13.9.1
pysam==0.23.0
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-json-logger==3.2.1
pytz==2024.1
PyYAML==6.0.2
pyzmq==26.2.0
qnorm==0.8.1
qtconsole==5.6.1
QtPy==2.4.1
referencing==0.30.2
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.9.4
rpds-py==0.22.3
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.15.1
seaborn==0.13.2
Send2Trash==1.8.2
setuptools==75.8.0
simplejson==3.20.1
sip==6.10.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.5
stack-data==0.2.0
statsmodels==0.14.4
tabulate==0.9.0
tensorboard==2.17.0
tensorboard_data_server==0.7.0
tensorflow==2.17.0
tensorflow_estimator==2.15.0
tensorflow-io-gcs-filesystem==0.37.1
termcolor==2.1.0
terminado==0.17.1
threadpoolctl==3.5.0
tifffile==2025.2.18
tinycss2==1.4.0
tomli==2.0.1
toolz==1.0.0
tornado==6.4.2
tract_querier==0.1
traitlets==5.14.3
typing_extensions==4.12.2
tzdata==2024.1
urllib3==2.3.0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.1.3
wheel==0.45.1
widgetsnbextension==4.0.13
wrapt==1.14.0
zipp==3.21.0
