### ISSUE TITLE
AttributeError in running genes.ipynb

### ISSUE THREAD

**Issue by snat1505027** [calico/basenji#31]
When i try to run the command in google colab
`! basenji_hdf5_genes.py -g data/human.hg19.genome -l 131072 -c 0.333 -p 3 -t data/heart_wigs.txt -w 128 data/hg19.ml.fa data/gencode_chr9.gtf data/gencode_chr9.h5`

I get the following error:

```
Traceback (most recent call last):
  File "basenji_hdf5_genes.py", line 465, in <module>
    main()
  File "basenji_hdf5_genes.py", line 102, in main
    check_wigs(options.target_wigs_file)
  File "basenji_hdf5_genes.py", line 357, in check_wigs
    for wig_file in target_wigs_df.file:
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'file'
```

**Comment by davek44** [comment]
Hi, I pushed a new tutorial that should fix the problem. Thanks!
