### ISSUE TITLE
Basset-style peak prediction problem

### ISSUE THREAD

**Issue by ramzan1990** [calico/basenji#73]
Hello. I am following the instructions in manuscripts/basset to make prediction using my bed files. I have modified the targets and ran make_data.sh without problems. Next, I changed the "units": 164 to 2 in params_basset.json since I want to use two bed files. However, when I executed basenji_train.py -k -o train_basset --rc params_basset.json data_basset I got that --rc is unknown parameter. Removing that parameter resulted in the following exception: 

Traceback (most recent call last):
  File "/home/user/basenji-master/bin/basenji_train.py", line 165, in <module>
    main()
  File "/home/user/basenji-master/bin/basenji_train.py", line 154, in main
    seqnn_trainer.fit_keras(seqnn_model)
  File "/home/user/basenji-master/basenji/trainer.py", line 132, in fit_keras
    validation_steps=self.eval_epoch_batches[0])
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1100, in fit
    tmp_logs = self.train_function(iterator)
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 888, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/user/anaconda3/envs/basenji/lib/python3.6/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [200,448,2] vs. [200,64,2]
	 [[node LogicalAnd_2 (defined at /basenji-master/basenji/metrics.py:65) ]] [Op:__inference_train_function_5687]

Function call stack:
train_function

Setting the batch size to 1 makes the code run, but I dont know if the results are correct. Please advise what is wrong!

**Comment by davek44** [comment]
This looks like a mismatch in the sequence length to me. Perhaps your model is doing too much or too little pooling operations to fit the targets length.
