### ISSUE TITLE
Error training Basset-style model (Incompatible shapes: [200,448,164] vs. [200,64,164])

### ISSUE THREAD

**Issue by mjbetti** [calico/basenji#75]
Hi, I've been attempting to train a Basset-style mode using the guidelines that you outlined here: https://github.com/calico/basenji/tree/master/manuscripts/basset

When I get to the actual training step, though, using the included ```params_basset.json``` file, I keep getting the following incompatible dimensions error message, in which it appears that the ```batch_size``` value of 64 is being multiplied by 7:
```
Total params: 5,967,782
Trainable params: 5,960,460
Non-trainable params: 7,322
__________________________________________________________________________________________________
None
model_strides [192]
target_lengths [7]
target_crops [0]
2021-02-07 16:50:08.427245: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
Epoch 1/10000
Traceback (most recent call last):
  File "/home/bettimj/basenji/bin/basenji_train.py", line 165, in <module>
    main()
  File "/home/bettimj/basenji/bin/basenji_train.py", line 154, in main
    seqnn_trainer.fit_keras(seqnn_model)
  File "/gpfs23/scratch/bettimj/basenji/basenji/trainer.py", line 126, in fit_keras
    seqnn_model.model.fit(
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/bettimj/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Incompatible shapes: [200,448,164] vs. [200,64,164]
	 [[node LogicalAnd_6 (defined at gpfs23/scratch/bettimj/basenji/basenji/metrics.py:65) ]] [Op:__inference_train_function_6085]

Function call stack:
train_function
```

The only way that I have been able to get the script to run so far is by decreasing the ```batch_size``` parameter in the JSON file down to 1. Do you know what might be causing this issue on my end?

Thank you so much for your help!

**Comment by davek44** [comment]
Hi, the problem here was that I changed the way my convolution block was handling padding, which caused my overcomplicated flattening to fail. I introduced a simple dense block that takes a flatten operation instead, and Basset-style now appears to be working fine. Pull the latest from master and make sure you use the new parameters file in the basset directory.
