### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by cmlakhan** [calico/basenji#77]
I am trying to install basenji on a AWS instance and am getting an installation error.  I am using the deep learning AMI but I have created a new conda environment based on the your environment.yml file.  I cloned your repo and simply ran the following:

 conda env create -f environment.yml

but get the following error:

```
  Downloading cooler-0.8.10-py2.py3-none-any.whl (100 kB)
Requirement already satisfied: pandas in /home/ubuntu/anaconda3/envs/basenji/lib/python3.8/site-packages (from cooler->-r /home/ubuntu/basenji/condaenv.lp6usk6h.requirements.txt (line 1)) (1.2.1)
Requirement already satisfied: scipy>=0.16 in /home/ubuntu/anaconda3/envs/basenji/lib/python3.8/site-packages (from cooler->-r /home/ubuntu/basenji/condaenv.lp6usk6h.requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: six in /home/ubuntu/anaconda3/envs/basenji/lib/python3.8/site-packages (from cooler->-r /home/ubuntu/basenji/condaenv.lp6usk6h.requirements.txt (line 1)) (1.15.0)
Requirement already satisfied: numpy>=1.9 in /home/ubuntu/anaconda3/envs/basenji/lib/python3.8/site-packages (from cooler->-r /home/ubuntu/basenji/condaenv.lp6usk6h.requirements.txt (line 1)) (1.19.2)
Requirement already satisfied: h5py>=2.5 in /home/ubuntu/anaconda3/envs/basenji/lib/python3.8/site-packages (from cooler->-r /home/ubuntu/basenji/condaenv.lp6usk6h.requirements.txt (line 1)) (2.10.0)
Collecting click>=7
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting cytoolz<0.11
  Downloading cytoolz-0.10.1.tar.gz (475 kB)
Collecting toolz>=0.8.0
  Downloading toolz-0.11.1-py3-none-any.whl (55 kB)
Collecting cooltools
  Downloading cooltools-0.3.2.tar.gz (8.0 MB)

Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/envs/basenji/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bg_rlbyb/cooltools_a89413fd2ba348348ddfd8187e45fe39/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bg_rlbyb/cooltools_a89413fd2ba348348ddfd8187e45fe39/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-m0ec64i3
         cwd: /tmp/pip-install-bg_rlbyb/cooltools_a89413fd2ba348348ddfd8187e45fe39/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bg_rlbyb/cooltools_a89413fd2ba348348ddfd8187e45fe39/setup.py", line 9, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
                                                                                                                                                                failed

CondaEnvException: Pip failed

```

Any idea why?  I tried it once by installing cython but that did not seem to work

**Comment by cmlakhan** [comment]
It seems that adding cython to the environment.yml file seemed to work

**Comment by davek44** [comment]
Great, I'll add it to the master version. Thanks!
